packages:
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': true
  core-js: false
  core-js-pure: false
  esbuild: true
  ffmpeg-ffprobe-static: true
  nx: true

catalog:
  '@preact/signals': ^1.2.1
  '@types/node': ^20.19.0
  clsx: ^2.0.0
  jsdom: ^29.1.0
  preact: ^10.19.2
  vite: ^8.0.0
  vitest: ^4.1.0

overrides:
  '@types/node': ^20.19.0
  cytoscape: 3.28.1
