name: Deploy Documentation to GitHub Pages

on: workflow_dispatch

permissions: {}

env:
  HUSKY: 0

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit
          disable-sudo: true
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run examples:build
      - run: pnpm run editor:showcase
      - run: pnpm run docs:build
        env:
          NODE_OPTIONS: '--max-old-space-size=8192'
      - uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./packages/docs/build
          external_repository: canvas-commons/canvas-commons.github.io
