name: Publish Packages to NPM

on:
  workflow_dispatch:
    inputs:
      releaseType:
        type: choice
        description: Release type
        required: true
        options:
          - release
          - prerelease
          - graduate

env:
  HUSKY: 0

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      NPM_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      GH_TOKEN: ${{secrets.PUBLISH_TOKEN}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{secrets.PUBLISH_TOKEN}}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: npm
      - run: git config --global user.email "221908586+canvas-commons-bot@users.noreply.github.com"
      - run: git config --global user.name "canvas-commons-bot"
      - run: npm ci
      - run: npx lerna run build
      - if: ${{ inputs.releaseType == 'release' }}
        run: npx lerna publish --yes
      - if: ${{ inputs.releaseType == 'prerelease' }}
        run: npx lerna publish --yes --conventional-prerelease --dist-tag alpha
      - if: ${{ inputs.releaseType == 'graduate' }}
        run: npx lerna publish --yes --conventional-graduate
