name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  HUSKY: 0

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{secrets.PUBLISH_TOKEN}}
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm exec changeset version && pnpm install --lockfile-only
          publish: pnpm exec changeset publish
          createGithubReleases: true
          commit: 'chore(release): version packages'
          title: 'chore(release): version packages'
        env:
          GITHUB_TOKEN: ${{secrets.PUBLISH_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
