import type {FiddleVendorManifest} from '@canvas-commons/fiddle/manifest';
import {usePluginData} from '@docusaurus/useGlobalData';

function isVendorManifest(value: unknown): value is FiddleVendorManifest {
  return (
    typeof value === 'object' &&
    value !== null &&
    'frameUrl' in value &&
    typeof value.frameUrl === 'string' &&
    'harnessUrl' in value &&
    typeof value.harnessUrl === 'string' &&
    'hash' in value &&
    typeof value.hash === 'string' &&
    'stamp' in value &&
    typeof value.stamp === 'string' &&
    'engineVersion' in value &&
    typeof value.engineVersion === 'string' &&
    (!('typesUrl' in value) || typeof value.typesUrl === 'string') &&
    (!('tsVersion' in value) || typeof value.tsVersion === 'string') &&
    'importMap' in value &&
    typeof value.importMap === 'object' &&
    value.importMap !== null &&
    'imports' in value.importMap &&
    typeof value.importMap.imports === 'object' &&
    value.importMap.imports !== null &&
    Object.values(value.importMap.imports).every(url => typeof url === 'string')
  );
}

/** Read the shared vendor manifest generated by the site's fiddle plugin. */
export function useFiddleManifest(): FiddleVendorManifest | null {
  const data = usePluginData('docusaurus-fiddle-plugin');
  return isVendorManifest(data) ? data : null;
}
